remote_theme: abhinavs/moonwalk
title: Slugville
author: slugcat77
description: Slugcat's awesome blog about various things (primarily the Binding of Isaac)

permalink: /:slug

favicon: "./logo.png"

theme_config:
  appearance: "dark"
  appearance_toggle: true
  back_home_text: "home..."
  date_format: "%Y-%m-%d"
  show_description: true
  show_navbar: false
  show_footer: true
  show_copyright: true
  # following keys are used to create home layout
  show_projects: true
  show_blog: true
  show_old_projects: false
  show_misc_list: true
  show_reading_time: true
  show_tags: false
  #options for home page
  home:
    title_projects: TBoI Mods
    title_blog: Blog Posts

highlighter: rouge